--DATA PREPARATION AND UNDERSTANDING
--1.What is the total number of rows in each of the 3 tables in the database?
select count(*) from [dbo].[Customer]
select count(*) from [dbo].[prod_cat_info]
select count(*) from [dbo].[Transactions]

--2.What is the total number of transactions that have a return?
select count([transaction_id]) from [dbo].[Transactions] 
where [Qty]<0

/* 3.As you would have noticed, the dates provided across the datasets are not in a correct format. 
As first steps, pls convert the date variables into valid date formats before proceeding ahead.
*/
select [customer_Id], convert(date,[DOB],103) as DOB , convert(date,[tran_date],103) as trans_date from [dbo].[Customer]c
inner join [dbo].[Transactions] t on c.[customer_Id]=t.[cust_id]

/*4.What is the time range of the transaction data available for analysis? 
Show the output in number of days, months and years simultaneously in different columns.
*/
select DATEDIFF(year,min(convert(date,[tran_date],103)),max(convert(date,[tran_date],103))) as year,
DATEDIFF(month,min(convert(date,[tran_date],103)),max(convert(date,[tran_date],103)))as months,
DATEDIFF(day,min(convert(date,[tran_date],103)),max(convert(date,[tran_date],103))) as days from [dbo].[Transactions]

--5.Which product category does the sub-category “DIY” belong to?
select [prod_cat] from [dbo].[prod_cat_info] where [prod_subcat]='DIY'

--DATA ANALYSIS
--1.Which channel is most frequently used for transactions?
SELECT top 1([Store_type]) as channel , COUNT(Store_type) as frequency FROM [dbo].[Transactions]
group by [Store_type]
order by 2 desc

--2.What is the count of Male and Female customers in the database?
select [Gender],count(Gender) as total from [dbo].[Customer] where [Gender] is not null
group by gender 

--3.From which city do we have the maximum number of customers and how many?
select top 1 [city_code] , count([customer_Id]) as num_cust from [dbo].[Customer] 
group by [city_code]
order by 2 desc

--4.How many sub-categories are there under the Books category?
select [prod_cat] , count([prod_subcat]) no_of_subcat from [dbo].[prod_cat_info]
group by [prod_cat] having [prod_cat]='books'

--5.What is the maximum quantity of products ever ordered?
select [prod_cat],[prod_subcat],max(abs(cast(t.[Qty] as int))) as total from [dbo].[Transactions] t 
inner join [dbo].[prod_cat_info] p on p.[prod_cat_code]=t.[prod_cat_code] and p.[prod_sub_cat_code]=t.[prod_subcat_code]
group by [prod_cat],[prod_subcat]

--6.What is the net total revenue generated in categories Electronics and Books?
select p.[prod_cat] , sum(cast([total_amt] as float))as net_total from [dbo].[Transactions] t 
inner join [dbo].[prod_cat_info] p on t.prod_cat_code=p.[prod_cat_code]
group by p.[prod_cat]
having p.[prod_cat] in ('books','electronics')

--7.How many customers have >10 transactions with us, excluding returns?
select count(q.[cust_id])from (select [cust_id], count([cust_id])ct from [dbo].[Customer]c
inner join [dbo].[Transactions] t on c.[customer_Id]=t.[cust_id] where [Qty]>0
group by [cust_id])q where q.ct>10

--8.What is the combined revenue earned from the “Electronics” & “Clothing” categories, from “Flagship stores”?
select p.[prod_cat],sum(convert(float,[total_amt]))revenue from [dbo].[prod_cat_info] p
inner join [dbo].[Transactions]t on p.[prod_cat_code]=t.[prod_cat_code]
where p.prod_cat in ('electronics','clothing') and t.[Store_type]='flagship store'
group by p.prod_cat

/*9.What is the total revenue generated from “Male” customers in “Electronics” category?
Output should display total revenue by prod sub-cat.
*/
select round(sum(cast(([total_amt]) as float)),2) as revenue from [dbo].[Customer]c 
inner join [dbo].[Transactions] t on c.[customer_Id]=t.[cust_id]
inner join [dbo].[prod_cat_info] p on t.[prod_cat_code]=p.[prod_cat_code] and t.[prod_subcat_code]=p.[prod_sub_cat_code]
where c.Gender='M' and p.prod_cat='Electronics'

--10.What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales?
select top 5 p.prod_cat ,p.prod_subcat,
round(sum(case when convert(float,[total_amt])>0 then convert(float,[total_amt]) end )*100/ (select sum(convert(float,[total_amt])) 
from [dbo].[Transactions] where convert(float,[total_amt])>0 ),2) as sales_percent,
round(sum(case when convert(float,[total_amt])<0 then convert(float,[total_amt]) end )*100/ (select sum(convert(float,[total_amt])) 
from [dbo].[Transactions] where convert(float,[total_amt])<0 ),2) as returns_percent
from [dbo].[Transactions] t inner join [dbo].[prod_cat_info] p 
on p.prod_cat_code=t.prod_cat_code and p.prod_sub_cat_code=t.prod_subcat_code
group by p.prod_cat , p.prod_subcat order by sales_percent desc

---11.For all customers aged between 25 to 35 years find what is the net total revenue generated by 
--these consumers in last 30 days of transactions from max transaction date available in the data?	 
select sum(convert(float,t.total_amt)) net from [dbo].[Customer] c 
inner join [dbo].[Transactions] t on t.cust_id=c.customer_Id 
where convert(date,[tran_date],103) > (select dateadd(day,-30,(max(convert(date,[tran_date],103)))) from [dbo].[Transactions]) 
      and datediff(year,convert(date,c.[DOB],103),getdate()) between 25 and 30

--12.Which prod category has seen the max value of returns in last 3 months of transaction ?
select top 1 p.prod_cat,sum(convert(float,t.[total_amt])) as net_return from [dbo].[Transactions] t 
inner join [dbo].[prod_cat_info] p on t.prod_cat_code=p.prod_cat_code and t.prod_subcat_code=p.prod_sub_cat_code
where  convert(date,[tran_date],103)>(select dateadd(month,-3, max(convert(date,[tran_date],103))) from [dbo].[Transactions])
group by p.prod_cat
order by 2 desc

--13. which storetype sells max products by value of sales amount and qty sold ?
select top 1 [Store_type] ,round(sum(convert(float,[total_amt])),2) total, sum(convert(float,[Qty])) qty from [dbo].[Transactions]
group by [Store_type]
order by 2 desc

--14.what are the categories for avg revenue is above overall avg ?
 select w.prod_cat , round(w.avg_cat,2) from 
 (select p.[prod_cat] ,AVG(convert(float,[total_amt])) as avg_cat from [dbo].[Transactions] q 
 inner join [dbo].[prod_cat_info] p on p.prod_cat_code=q.prod_cat_code 
 group by p.[prod_cat]) w
 where w.avg_cat>(select AVG(convert(float,[total_amt])) from [dbo].[Transactions])

---15.find average and total revenue by each subcat for the catgry which are among the top 5 cat in terms of qty sold ?
select P.prod_cat , P.prod_subcat, AVG(cast(total_amt as float)) as Average_Revenue,
SUM(cast(total_amt as float)) as Total_Revenue from [dbo].[Transactions] as T
INNER JOIN [dbo].[prod_cat_info]as P
ON P.prod_cat_code = T.prod_cat_code AND P.prod_sub_cat_code = T.prod_subcat_code
where P.prod_cat in 
(select prod_cat from (select top 5 P.prod_cat ,sum(Cast(Qty as int)) qty from [dbo].[prod_cat_info] as P
inner join [dbo].[Transactions] as T
ON P.prod_cat_code = T.prod_cat_code AND P.prod_sub_cat_code = T.prod_subcat_code
group by P.prod_cat
order by 2 desc)w)
group by P.prod_cat,P.prod_subcat


